# Default values for tensorflow-serving.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Kubernetes configuration
## support NodePort, LoadBalancer
##
serviceType: LoadBalancer

grpcServicePort: 9090
restServicePort: 80
replicas: 1

image:
  repository: "tensorflow/serving"
  tag: "1.12.0"
  # tag: "1.12.0-gpu"
  pullPolicy: "IfNotPresent"
resources: {}
  #  limits:
  #    cpu: 1.0
  #    memory: 512Mi
  #    nvidia.com/gpu: 1
  #  requests:
  #    cpu: 1.0
  #    memory: 512Mi
  #    nvidia.com/gpu: 1


## The command and args to run the pod
grpcPort: 8500
restPort: 8501
modelName: "model-name"
modelBasePath: "model-base-path"

persistence:
  enabled: false
  storageClass: ""
  size: 10Gi
  accessMode: ReadWriteOnce
 # matchLabels: {}
