apiVersion: v1
kind: Service
metadata:
  name: {{ template "tensorflow-serving.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "tensorflow-serving.chart" . }}
    app: {{ template "tensorflow-serving.name" . }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: grpc-service-port
      port: {{ .Values.grpcServicePort }}
      targetPort: grpc-port
    - name: http-service-port
      port: {{ .Values.restServicePort }}
      targetPort: http-port
  selector:
    release: {{ .Release.Name | quote }}
    app: {{ template "tensorflow-serving.name" . }}
